### ISSUE TITLE
Error: Not a valid -value pair

### ISSUE THREAD

**Issue by dmwright94** [aws/aws-elastic-beanstalk-cli-setup#18]
I've followed the setup instructions in [this doc](https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/eb-cli3-install-osx.html) but when I run 

`eb init` 

I receive the following error after I select the default region: 

> ERROR: ServiceError - 'test/20190515/us-west-2/elasticbeanstalk/aws4_request' not a valid key=value pair (missing equal-sign) in Authorization header: 'AWS4-HMAC-SHA256 Credential=eb test/20190515/us-west-2/elasticbeanstalk/aws4_request, SignedHeaders=content-type;host;x-amz-content-sha256;x-amz-date, Signature=b4c95b623359d11e2cb2c648d713c1be54302f67d5f8a662c118bdb41e76d0dd'.

the result of `$ eb --version` is:
`EB CLI 3.15.0 (Python 3.5.1)`

**Comment by rahulrajaram** [comment]
Hi @dmwright94 ,

Thanks for reaching out. This looks like an AWS credentials-related issue. Can you verify whether your AWS access ID and secret key have been correctly set in your `~/.aws/credentials` and/or `~/.aws/config` files? Also ensure there are no unnecessary whitespaces. Standard examples are shown [here](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-files.html#cli-configure-files-where).

**Comment by dmwright94** [comment]
That solved it. Thank you!
