### ISSUE TITLE
bundled_installer stuck at Installing Python-3.7.2

### ISSUE THREAD

**Issue by shabin-slr** [aws/aws-elastic-beanstalk-cli-setup#21]
I'm trying to install the CLI on Ubuntu 18.08.
When I run bundle_installer I see the following logs : 

```console
> I. Installing Python                          
> *************************************************************
> 1. Determining whether pyenv is already installed and in PATH
> *************************************************************
>     - pyenv was not found in PATH.
> 
> *********************************************************
> 2. Determining whether pyenv should be cloned from GitHub
> *********************************************************
>     - pyenv git repository already cloned to /home/shabin/.pyenv-repository. Won't attempt to clone again.
> 
> *******************************************
> 3. Temporarily export necessary pyenv paths
> *******************************************
> 
> ****************************************************************************
> 4. Checking whether Python can be downloaded (through curl, wget, or aria2c)
> ****************************************************************************
> 
> **************************
> 5. Installing Python 3.7.2
> **************************
> Downloading Python-3.7.2.tar.xz...
> -> https://www.python.org/ftp/python/3.7.2/Python-3.7.2.tar.xz
> Installing Python-3.7.2...`
```

After reaching step 5, the script is stuck there like for ever. Nothing gets printed in the console after this. I hit Ctrl+C after like 20 minutes and then see this when the program exits : 

```console
> BUILD FAILED (Ubuntu 18.04 using python-build 20180424)
> 
> Inspect or clean up the working tree at /tmp/python-build.20190520135926.5003
> Results logged to /tmp/python-build.20190520135926.5003.log
> 
> Last 10 log lines:
> /tmp/python-build.20190520135926.5003 ~/EBS_CLI/aws-elastic-beanstalk-cli-setup/scripts
> /tmp/python-build.20190520135926.5003/Python-3.7.2 /tmp/python-build.20190520135926.5003 ~/EBS_CLI/aws-elastic-beanstalk-cli-setup/scripts
> checking build system type...    Exiting due to failure
> 
> II. Creating self-contained EBCLI installation
> ./aws-elastic-beanstalk-cli-setup/scripts/bundled_installer: line 51: /home/shabin/.pyenv/versions/3.7.2/bin/python: No such file or directory
> ./aws-elastic-beanstalk-cli-setup/scripts/bundled_installer: line 28: echo_with_indentation: command not found
```

**Comment by rahulrajaram** [comment]
Thanks for reaching out, @shabin-slr. Python installation can take time. I'd recommend taking a look at `/tmp/python-build.20190520135926.5003.log` to see if there is any useful information in that file. Specifically, can you look for the word "error" (and other variants such as "ERROR"). If there are no indications of problems, it is likely that Python is just taking too long to install.

**Comment by mohamedainab** [comment]
I am having a similar issue as the poster. I can post the content of /tmp/python-build.20190616171815.51053.log if needed.

**Comment by joesilverstein** [comment]
Python installation takes forever when installing using the GitHub installation script (I'm assuming because the latest version is getting compiled). So unless you absolutely need the latest build for some reason, you could just install using pip instead and it will be done in seconds.
`pip3 install awsebcli --upgrade --user`.

**Comment by mohamedainab** [comment]
> Python installation takes forever when installing using the installation script (I'm assuming because the latest version is getting compiled). So unless you absolutely need the latest commit for some reason, you could just install the pre-compiled version using pip instead and it will be done in seconds.
> `pip3 install awsebcli --upgrade --user`.

Thanks. I have resolved it in a different way.

**Comment by issnoejasso** [comment]
> > Python installation takes forever when installing using the installation script (I'm assuming because the latest version is getting compiled). So unless you absolutely need the latest commit for some reason, you could just install the pre-compiled version using pip instead and it will be done in seconds.
> > `pip3 install awsebcli --upgrade --user`.
> 
> Thanks. I have resolved it in a different way.
Can you share the steps you follow @mohamedainab ? Thanks. 🤓

**Comment by kamlekar** [comment]
@mohamedainab please care to share your solution.

**Comment by kamlekar** [comment]
For me this worked on mac:

    brew install awsebcli
