### ISSUE TITLE
Install fails when trying to install on Ubuntu 18.04

### ISSUE THREAD

**Issue by tomroima** [aws/aws-elastic-beanstalk-cli-setup#25]
Hello, i have been trying to install this CLI to be able to ssh into my elasticbeanstalk machine, but it fails. 

At the beggining it failed because it lacked zlib1g, but i solved it with: `sudo apt-get install zlib1g-dev`.

Then it failed because it lacked the '_ctypes', then i did: `sudo apt-get install libffi-dev` and went on.

Now i'm stuck at this, after this message:
```
Last 10 log lines:
		install|*) ensurepip="" ;; \
	esac; \
	 ./python -E -m ensurepip \
		$ensurepip --root=/ ; \
fi
Looking in links: /tmp/tmpocghb8ub
Collecting setuptools
Collecting pip
Installing collected packages: setuptools, pip
Successfully installed pip-18.1 setuptools-40.6.2
   Exiting due to failure

==============================================
II. Creating self-contained EBCLI installation
==============================================
./aws-elastic-beanstalk-cli-setup/scripts/bundled_installer: línea 51: /home/tomroima/.pyenv/versions/3.7.2/bin/python: No existe el archivo o el directorio
./aws-elastic-beanstalk-cli-setup/scripts/bundled_installer: línea 28: echo_with_indentation: orden no encontrada
```
Did anyone else hit this problem? Is there anything else that can be done?

Thanks in advance

**Comment by rahulrajaram** [comment]
@tomroima , thanks for reaching out. We should update installation instructions for Ubuntu to include zlib, openssl, libffi, etc.

As for the issue you are facing now, I think I have an idea of what the problem is, but I need to run a few tests.

Can you delete the `.pyenv-repository` in your home directory and rerun the `bundled_installer`? If that doesn't work, install Python through other means and run the `ebcli_installer.py` as a Python script.

**Comment by tomroima** [comment]
Thank you for the quick response @rahulrajaram. I tried to do what you said above, but i didn't work and the error was the same.

When i tried to run it as a python script, it doesn't find virtualenv, so it fails, but after installing the dependency with `sudo apt-get install virtualenv` it finished the installation.

Thank you @rahulrajaram

**Comment by rahulrajaram** [comment]
@tomroima , thanks for your response. I am curious to know if `which pyenv` returns anything. I'd like to fix the problem of `python` not getting installed properly.

**Comment by tomroima** [comment]
@rahulrajaram Sure, here goes the gist.

https://gist.github.com/tomroima/0c36ce8a4943dc3d60096d0b93717167

**Comment by ltieman** [comment]
I'm having the same issue on Fedora 30

-> https://www.python.org/ftp/python/3.7.2/Python-3.7.2.tar.xz
Installing Python-3.7.2...
WARNING: The Python bz2 extension was not compiled. Missing the bzip2 lib?
WARNING: The Python readline extension was not compiled. Missing the GNU readline lib?
ERROR: The Python ssl extension was not compiled. Missing the OpenSSL lib?

Please consult to the Wiki page to fix the problem.
https://github.com/pyenv/pyenv/wiki/Common-build-problems


BUILD FAILED (Fedora 30 using python-build 20180424)

Inspect or clean up the working tree at /tmp/python-build.20190531084131.14907
Results logged to /tmp/python-build.20190531084131.14907.log

Last 10 log lines:
		install|*) ensurepip="" ;; \
	esac; \
	 ./python -E -m ensurepip \
		$ensurepip --root=/ ; \
fi
Looking in links: /tmp/tmpbrvojxz9
Collecting setuptools
Collecting pip
Installing collected packages: setuptools, pip
Successfully installed pip-18.1 setuptools-40.6.2
   Exiting due to failure


I've checked and I have both bzip2, openssl and readline installed and up-to-date at bzip2-1.0.6-29.fc30.x86_64, openssl-1:1.1.1b-5.fc30.x86_64, and readline-8.0-2.fc30.x86_64.  Is there an issue with version compatibility?

**Comment by rahulrajaram** [comment]
@tomroima , from the build log, it looks like missing openssl is causing the problem. `apt install libssl-dev` should fix it. Let me know if that's not so. This would be another good tip to add to the readme.

**Comment by ltieman** [comment]
Just wanted to note that in my instance of the issue, I've validated that openssl is installed.  

However, it appears it needs the -devel versions of the libraries.

**Comment by rahulrajaram** [comment]
@ltieman , that's because you are on Fedora. @tomroima is using Ubuntu. Thanks for the useful information, though.

**Comment by jazzyjackson** [comment]
Hi, I am also arriving at this error using the install script on Mac OSX, I'm getting messages about OpenSSL python extension missing. While that may be a personal problem, the install script is exiting with this "echo_with_indentation" which is a function not defined in the bash script. It took a while to finally scroll up at the real error message, "ERROR: The Python ssl extension was not compiled"

I've tried using brew install for python, openssl, readline, and everything looks up to date. I'd appreciate any advice on how to get past this -- this is the first time I've used this macbook for pyenv so I don't know if it could be some kind of version conflict (`brew install python` installs 3.7.3)


```
**************************
5. Installing Python 3.7.2
**************************
python-build: use openssl from homebrew
python-build: use readline from homebrew
Downloading Python-3.7.2.tar.xz...
-> https://www.python.org/ftp/python/3.7.2/Python-3.7.2.tar.xz
Installing Python-3.7.2...
python-build: use readline from homebrew
ERROR: The Python ssl extension was not compiled. Missing the OpenSSL lib?

Please consult to the Wiki page to fix the problem.
https://github.com/pyenv/pyenv/wiki/Common-build-problems


BUILD FAILED (OS X 10.12.6 using python-build 20180424)

Inspect or clean up the working tree at /var/folders/h6/ln5m_qq56px93vbgkc_w_rth0000gp/T/python-build.20190602220521.24692
Results logged to /var/folders/h6/ln5m_qq56px93vbgkc_w_rth0000gp/T/python-build.20190602220521.24692.log

Last 10 log lines:
			install|*) ensurepip="" ;; \
		esac; \
		 ./python.exe -E -m ensurepip \
			$ensurepip --root=/ ; \
	fi
Looking in links: /var/folders/h6/ln5m_qq56px93vbgkc_w_rth0000gp/T/tmp6yq81rq5
Collecting setuptools
Collecting pip
Installing collected packages: setuptools, pip
Successfully installed pip-18.1 setuptools-40.6.2
   Exiting due to failure

==============================================
II. Creating self-contained EBCLI installation
==============================================
./aws-elastic-beanstalk-cli-setup/scripts/bundled_installer: line 51: /Users/istrauss/.pyenv/versions/3.7.2/bin/python: No such file or directory
./aws-elastic-beanstalk-cli-setup/scripts/bundled_installer: line 28: echo_with_indentation: command not found
```

**Comment by rahulrajaram** [comment]
@jazzyjackson , this should really have been a separate issue. FFR, please create new Issues for independent problems.

That being, to get around your problem install `virtualenv`, and then run the file, `scripts/ebcli_installer.py` as a Python script.

**Comment by jazzyjackson** [comment]
@rahulrajaram thanks for the recommendation

I arrived at this issue by searching for "echo_with_indentation: command not found" which threw me off for a while, so consider that my contribution to this ticket

**Comment by tomroima** [comment]
@rahulrajaram I have `OpenSSL 1.1.0g  2 Nov 2017` installed on my system, and it still failed. 
Anyways, i wanted to use this cli to gain ssh access to elastic beanstalk environments. I ended up needing a bastion host to communicate with the machines, and ended up using plain ssh through the bastion host.

**Comment by rahulrajaram** [comment]
@jazzyjackson , okay, good point.

@tomroima , sorry for the inconvenience.

> ... and it still failed.

Do you mean that despite being able to install `eb` as you have indicated [here](https://github.com/aws/aws-elastic-beanstalk-cli-setup/issues/25#issuecomment-497245002), you were unable to SSH into your instance?

**Comment by Mohammad-Kabajah** [comment]
if you install all of the following dependencies 
sudo apt-get install build-essential checkinstall
sudo apt-get install libreadline-gplv2-dev libncursesw5-dev libssl-dev \
    libsqlite3-dev tk-dev libgdbm-dev libc6-dev libbz2-dev libffi-dev zlib1g-dev
the command worked for me after installing them, 
you might also want to install docker: https://docs.docker.com/install/linux/docker-ce/ubuntu/

**Comment by tomroima** [comment]
@rahulrajaram Sorry, i meant that even with openssl installed, the installation failed. 
I was just able to try the command installing it from the python script. 
It failed probably because my instances were in a private network, or so i think. I just needed to ssh into the instances, which i accomplished by using the bastion host with the right permissions.

**Comment by HakimBenyoucef** [comment]
@Mohammad-Kabajah Thank you!!! your solution saved my day
