### ISSUE TITLE
eb executable opens a new terminal

### ISSUE THREAD

**Issue by rtarnaud** [aws/aws-elastic-beanstalk-cli-setup#30]
I have installed eb-cli using this repo on Windows and encountered the bug described here  #19.

I followed the troubleshooting advice given in response and it completed the install successfully.

However, when I run the eb executable in the shell, it opens another one and run the command in the latter, which is rather annoying. Is it by design or did I mess up with the config?

**Comment by rahulrajaram** [comment]
Yes, it is by design. That's the only way we could get `eb` to operate inside a virtualenv. If you don't want a new shell, please use PowerShell.

**Comment by rtarnaud** [comment]
Hm ok. Thanks for your blazing fast response then!
