### ISSUE TITLE
Need help in cleaning installation : would like to use systemwide Python 

### ISSUE THREAD

**Issue by arangari** [aws/aws-elastic-beanstalk-cli-setup#32]
I had stopped the installation in between as I want to install the Python3.x for the system.
I am not finding this easily.

can I just remove .pyenv ?

**Comment by arangari** [comment]
Also, I have installed 3.7.3 python from 
https://www.python.org/ftp/python/3.7.3/python-3.7.3-macosx10.9.pkg

**Comment by rahulrajaram** [comment]
@arangari , thanks for reaching out. Yes, delete `~/.pyenv`, and `~/.pyenv-repository`. Then you can simply run `scripts/ebcli_installer.py` using the Python you have to install the EBCLI.

**Comment by arangari** [comment]
@rahulrajaram  - thanks for the steps. 
I still see the errors now for step you told. Please look at the output below.

```
[arangari@arangari-MBP]:~/Desktop/aws-elastic-beanstalk-cli-setup (master)$ rm -rf ~/.pyenv
.pyenv/            .pyenv-repository/ 
[arangari@arangari-MBP]:~/Desktop/aws-elastic-beanstalk-cli-setup (master)$ rm -rf ~/.pyenv*
[arangari@arangari-MBP]:~/Desktop/aws-elastic-beanstalk-cli-setup (master)$ scripts/ebcli_installer.py
-bash: scripts/ebcli_installer.py: Permission denied
[arangari@arangari-MBP]:~/Desktop/aws-elastic-beanstalk-cli-setup (master)$ python3 !$
python3 scripts/ebcli_installer.py

***********************************
1. Locating virtualenv installation
***********************************
ERROR: Could not find and "virtualenv" installed. Ensurevirtualenv is installed and that it is in PATH before executingthis script.

******************************************
2. Creating exclusive virtualenv for EBCLI
******************************************
/bin/sh: virtualenv: command not found
[arangari@arangari-MBP]:~/Desktop/aws-elastic-beanstalk-cli-setup (master)$ 

```

**Comment by arangari** [comment]
installed virtualenv and i was able to complete installation. however i got following errors logged during installation.
`  Building wheel for awsebcli (setup.py) ... error
  ERROR: Complete output from command /Library/Frameworks/Python.framework/Versions/3.7/bin/python3 -u -c 'import setuptools, tokenize;__file__='"'"'/private/var/folders/nh/grgs0f354qbgksg264ty919w0000gp/T/pip-install-m_5t83ty/awsebcli/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/nh/grgs0f354qbgksg264ty919w0000gp/T/pip-wheel-vcg8di2_ --python-tag cp37:
  ERROR: Warning: 'classifiers' should be a list, got type 'tuple'
  usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: -c --help [cmd1 cmd2 ...]
     or: -c --help-commands
     or: -c cmd --help
  
  error: invalid command 'bdist_wheel'
  ----------------------------------------
  ERROR: Failed building wheel for awsebcli
  Running setup.py clean for awsebcli
  Building wheel for cement (setup.py) ... error
  ERROR: Complete output from command /Library/Frameworks/Python.framework/Versions/3.7/bin/python3 -u -c 'import setuptools, tokenize;__file__='"'"'/private/var/folders/nh/grgs0f354qbgksg264ty919w0000gp/T/pip-install-m_5t83ty/cement/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/nh/grgs0f354qbgksg264ty919w0000gp/T/pip-wheel-oub3mr3l --python-tag cp37:
  ERROR: usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: -c --help [cmd1 cmd2 ...]
     or: -c --help-commands
     or: -c cmd --help
  
  error: invalid command 'bdist_wheel'
  ----------------------------------------
  ERROR: Failed building wheel for cement
  Running setup.py clean for cement
  Building wheel for future (setup.py) ... error
  ERROR: Complete output from command /Library/Frameworks/Python.framework/Versions/3.7/bin/python3 -u -c 'import setuptools, tokenize;__file__='"'"'/private/var/folders/nh/grgs0f354qbgksg264ty919w0000gp/T/pip-install-m_5t83ty/future/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/nh/grgs0f354qbgksg264ty919w0000gp/T/pip-wheel-49e2h4zz --python-tag cp37:
  ERROR: usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: -c --help [cmd1 cmd2 ...]
     or: -c --help-commands
     or: -c cmd --help
  
  error: invalid command 'bdist_wheel'
  ----------------------------------------
  ERROR: Failed building wheel for future
  Running setup.py clean for future
  Building wheel for pathspec (setup.py) ... error
  ERROR: Complete output from command /Library/Frameworks/Python.framework/Versions/3.7/bin/python3 -u -c 'import setuptools, tokenize;__file__='"'"'/private/var/folders/nh/grgs0f354qbgksg264ty919w0000gp/T/pip-install-m_5t83ty/pathspec/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/nh/grgs0f354qbgksg264ty919w0000gp/T/pip-wheel-2f_3tta_ --python-tag cp37:
  ERROR: usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: -c --help [cmd1 cmd2 ...]
     or: -c --help-commands
     or: -c cmd --help
  
  error: invalid command 'bdist_wheel'
  ----------------------------------------
  ERROR: Failed building wheel for pathspec
  Running setup.py clean for pathspec
  Building wheel for PyYAML (setup.py) ... error
  ERROR: Complete output from command /Library/Frameworks/Python.framework/Versions/3.7/bin/python3 -u -c 'import setuptools, tokenize;__file__='"'"'/private/var/folders/nh/grgs0f354qbgksg264ty919w0000gp/T/pip-install-m_5t83ty/PyYAML/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/nh/grgs0f354qbgksg264ty919w0000gp/T/pip-wheel-_6dsbv0q --python-tag cp37:
  ERROR: usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: -c --help [cmd1 cmd2 ...]
     or: -c --help-commands
     or: -c cmd --help
  
  error: invalid command 'bdist_wheel'
  ----------------------------------------
  ERROR: Failed building wheel for PyYAML
  Running setup.py clean for PyYAML
  Building wheel for termcolor (setup.py) ... error
  ERROR: Complete output from command /Library/Frameworks/Python.framework/Versions/3.7/bin/python3 -u -c 'import setuptools, tokenize;__file__='"'"'/private/var/folders/nh/grgs0f354qbgksg264ty919w0000gp/T/pip-install-m_5t83ty/termcolor/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/nh/grgs0f354qbgksg264ty919w0000gp/T/pip-wheel-u867of9j --python-tag cp37:
  ERROR: usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: -c --help [cmd1 cmd2 ...]
     or: -c --help-commands
     or: -c cmd --help
  
  error: invalid command 'bdist_wheel'
  ----------------------------------------
  ERROR: Failed building wheel for termcolor
  Running setup.py clean for termcolor
  Building wheel for dockerpty (setup.py) ... error
  ERROR: Complete output from command /Library/Frameworks/Python.framework/Versions/3.7/bin/python3 -u -c 'import setuptools, tokenize;__file__='"'"'/private/var/folders/nh/grgs0f354qbgksg264ty919w0000gp/T/pip-install-m_5t83ty/dockerpty/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/nh/grgs0f354qbgksg264ty919w0000gp/T/pip-wheel-vii1p1dq --python-tag cp37:
  ERROR: usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: -c --help [cmd1 cmd2 ...]
     or: -c --help-commands
     or: -c cmd --help
  
  error: invalid command 'bdist_wheel'
  ----------------------------------------
  ERROR: Failed building wheel for dockerpty
  Running setup.py clean for dockerpty
  Building wheel for texttable (setup.py) ... error
  ERROR: Complete output from command /Library/Frameworks/Python.framework/Versions/3.7/bin/python3 -u -c 'import setuptools, tokenize;__file__='"'"'/private/var/folders/nh/grgs0f354qbgksg264ty919w0000gp/T/pip-install-m_5t83ty/texttable/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/nh/grgs0f354qbgksg264ty919w0000gp/T/pip-wheel-yr8r95sz --python-tag cp37:
  ERROR: usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: -c --help [cmd1 cmd2 ...]
     or: -c --help-commands
     or: -c cmd --help
  
  error: invalid command 'bdist_wheel'
  ----------------------------------------
  ERROR: Failed building wheel for texttable
  Running setup.py clean for texttable
  Building wheel for docopt (setup.py) ... error
  ERROR: Complete output from command /Library/Frameworks/Python.framework/Versions/3.7/bin/python3 -u -c 'import setuptools, tokenize;__file__='"'"'/private/var/folders/nh/grgs0f354qbgksg264ty919w0000gp/T/pip-install-m_5t83ty/docopt/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/nh/grgs0f354qbgksg264ty919w0000gp/T/pip-wheel-7uz9uqpv --python-tag cp37:
  ERROR: usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: -c --help [cmd1 cmd2 ...]
     or: -c --help-commands
     or: -c cmd --help
  
  error: invalid command 'bdist_wheel'
  ----------------------------------------
  ERROR: Failed building wheel for docopt
  Running setup.py clean for docopt`

**Comment by arangari** [comment]
Also, i get below errors while executing 'eb'. 

[arangari@arangari-MBP]:~/Desktop/aws-elastic-beanstalk-cli-setup (master)$  echo 'export PATH="/Users/arangari/.ebcli-virtual-env/executables:$PATH"' >> ~/.bash_profile && source ~/.bash_profile
[arangari@arangari-MBP]:~/Desktop/aws-elastic-beanstalk-cli-setup (master)$ eb
Traceback (most recent call last):
  File "/Users/arangari/.ebcli-virtual-env/executables/eb", line 45, in <module>
    exit(_exec_cmd(['/Users/arangari/.ebcli-virtual-env/bin/eb'] + sys.argv[1:]))
  File "/Users/arangari/.ebcli-virtual-env/executables/eb", line 25, in _exec_cmd
    p = subprocess.Popen(args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

**Comment by rahulrajaram** [comment]
This is not a problem with the EBCLI. One of the libraries OS X ships with by default is defective/outdated. The solution reported [here](https://github.com/awslabs/aws-sam-cli/issues/509#issuecomment-400628879) might fix your problem. You might need to use `pip3` rather than `pip`. Also try the solution without the `--user` flag.

**Comment by arangari** [comment]
It does not work. 
Tried both. 

pip3 install  --upgrade setuptools
pip3 install  --user --upgrade setuptools.

**Comment by rahulrajaram** [comment]
That's unfortunate. The above commands should have solved your problem, but I guess there are multiple `pip`s and Python's on your computer.

As an aside, it is precisely to get around problems such as these that this repository provides a way to install `pip`/Python too.

**Comment by arangari** [comment]
I keep getting error for openssl, although script is downloading it.


`Downloading openssl-1.0.2k.tar.gz...
-> https://pyenv.github.io/pythons/6b3977c61f2aedf0f96367dcfb5c6e578cf37e7b8d913b4ecb6643c3cb88d8c0
Installing openssl-1.0.2k...
Installed openssl-1.0.2k to /Users/arangari/.pyenv/versions/3.7.2

python-build: use readline from homebrew
Downloading Python-3.7.2.tar.xz...
-> https://www.python.org/ftp/python/3.7.2/Python-3.7.2.tar.xz
Installing Python-3.7.2...
python-build: use readline from homebrew
ERROR: The Python ssl extension was not compiled. Missing the OpenSSL lib?`

**Comment by rahulrajaram** [comment]
Please check out the troubleshooting section for OS X in the README. This failure is covered.

**Comment by rahulrajaram** [comment]
Closing this issue as steps to remedy the problem have been recommended. Furthermore, the original issue has been addressed. For any new problems, please create new issues. Doing so would help locate solutions to problems far more easily.

**Comment by tskir** [comment]
I encountered exactly this problem, and googling "ERROR: Failed building wheel for docopt", this issue was the only hit.

For other people who follow the same trail and end up here: while the solution above (`pip3 install --upgrade setuptools`) did not work for me, what eventually worked is: **`pip3 install --upgrade pip setuptools`** (upgrading **both** pip and setuptools). Hope this helps someone.
