### ISSUE TITLE
Error during php application deployment on ubuntu 18.04

### ISSUE THREAD

**Issue by lopezchr** [aws/aws-elastic-beanstalk-cli-setup#37]
During deployment of a php application I had the following error:

`ERROR: FileNotFoundError - [Errno 2] No such file or directory: '/home/christian/Documentos/1DOC3-v3/a'`

I don't have any directory "a" in the project. what should I do?

**Comment by rahulrajaram** [comment]
Hi @lopezchr , thanks for reaching out. Is it `eb deploy` that you are running? Can you rerun with the `--deploy` argument and post the command as well as the stack trace?

**Comment by rahulrajaram** [comment]
Closing for the time being. Please feel free to reopen this issue or comment on it if the problem persists.
