### ISSUE TITLE
bundled_installer - pyenv was not found in PATH

### ISSUE THREAD

**Issue by Tyler-V** [aws/aws-elastic-beanstalk-cli-setup#38]
Followed the guide, ran into this issue. I've tried uninstalling python and reinstalling, still getting the following issue.

Also noticed it prompts me to install Python 3.7.3 on a clean install through the powershell script but its searching for 3.7.2?

![image](https://user-images.githubusercontent.com/3893234/60781843-06f95e80-a112-11e9-945f-f022233c8a85.png)

**Comment by rahulrajaram** [comment]
`pyenv` is failing to load in step 5 because you are running on Windows. Bash on Windows is not a medium we currently support. On Windows, Python installation takes an alternate path. Please install through PowerShell. You will however be able to use `eb` though Bash.

**Comment by rahulrajaram** [comment]
Closing this issue as a solution has been recommended.
