### ISSUE TITLE
[osx] failed installation leading to bizarre system-wide font corruption

### ISSUE THREAD

**Issue by the-vampiire** [aws/aws-elastic-beanstalk-cli-setup#39]
i tried following the directions to install using 

```sh
$ ./aws-elastic-beanstalk-cli-setup/scripts/bundled_installer
```

the installation failed. soon after my terminal started acting strange (not displaying any text). then my menu bar stopped displaying text altogether. it only displayed the outline of the dropdown menus. i had to restart by touch, luckily the logout button is the last one which led me to being able to restart. 

on restart i opened firefox and noticed the damage it had done to the fonts. now all of my fonts in firefox are screwed up as well as those in my terminal (i had been using nerd-fonts installed via homebrew). 

here is a sample of the font issues:

**firefox (fonts are massive, spaced out, and numeric chars rendering strangely)**
<img width="731" alt="Screen Shot 2019-07-18 at 11 48 40 PM" src="https://user-images.githubusercontent.com/25523682/61508151-2dec4600-a9d8-11e9-9caa-75645788931f.png">

**terminal (fonts are tiny and nerdfont icon glyphs are broken)**
<img width="565" alt="Screen Shot 2019-07-18 at 11 49 46 PM" src="https://user-images.githubusercontent.com/25523682/61508187-5b38f400-a9d8-11e9-9661-77338b2039a4.png">

i reran the installation to see if i could capture the error report. its the same as what i received the first time when everything began breaking (before the restart). here is the output:

```sh
==============================================
I. Installing Python                          
==============================================

*************************************************************
1. Determining whether pyenv is already installed and in PATH
*************************************************************
    - pyenv was not found in PATH.

*********************************************************
2. Determining whether pyenv should be cloned from GitHub
*********************************************************
    - pyenv git repository already cloned to /Users/vampiire/.pyenv-repository. Won't attempt to clone again.

*******************************************
3. Temporarily export necessary pyenv paths
*******************************************

****************************************************************************
4. Checking whether Python can be downloaded (through curl, wget, or aria2c)
****************************************************************************

************************************************************
5. Installing Python 3.7.2. This step may take a few minutes
************************************************************
python-build: use openssl from homebrew
python-build: use readline from homebrew
Downloading Python-3.7.2.tar.xz...
-> https://www.python.org/ftp/python/3.7.2/Python-3.7.2.tar.xz
Installing Python-3.7.2...
python-build: use readline from homebrew

BUILD FAILED (OS X 10.14.5 using python-build 20180424)

Inspect or clean up the working tree at /var/folders/6q/pkk5d6_j34d1vd9hf2ymct900000gn/T/python-build.20190718234320.30795
Results logged to /var/folders/6q/pkk5d6_j34d1vd9hf2ymct900000gn/T/python-build.20190718234320.30795.log

Last 10 log lines:
  File "/private/var/folders/6q/pkk5d6_j34d1vd9hf2ymct900000gn/T/python-build.20190718234320.30795/Python-3.7.2/Lib/ensurepip/__main__.py", line 5, in <module>
    sys.exit(ensurepip._main())
  File "/private/var/folders/6q/pkk5d6_j34d1vd9hf2ymct900000gn/T/python-build.20190718234320.30795/Python-3.7.2/Lib/ensurepip/__init__.py", line 204, in _main
    default_pip=args.default_pip,
  File "/private/var/folders/6q/pkk5d6_j34d1vd9hf2ymct900000gn/T/python-build.20190718234320.30795/Python-3.7.2/Lib/ensurepip/__init__.py", line 117, in _bootstrap
    return _run_pip(args + [p[0] for p in _PROJECTS], additional_paths)
  File "/private/var/folders/6q/pkk5d6_j34d1vd9hf2ymct900000gn/T/python-build.20190718234320.30795/Python-3.7.2/Lib/ensurepip/__init__.py", line 27, in _run_pip
    import pip._internal
zipimport.ZipImportError: can't decompress data; zlib not available
make: *** [install] Error 1
   Exiting due to failure

==============================================
II. Creating self-contained EBCLI installation
==============================================
./bundled_installer: line 51: /Users/vampiire/.pyenv/versions/3.7.2/bin/python: No such file or directory
./bundled_installer: line 28: echo_with_indentation: command not found
```

any help would be greatly appreciated. i dont even want the CLI anymore, just want to uninstall / revert whatever damage it has done and use the web interface in the future.

**Comment by the-vampiire** [comment]
for the record i have homebrew installed as well as python 3.7.2 before attempting this install.

**Comment by rahulrajaram** [comment]
Thanks for reaching out. This is bizarre indeed. This looks very much like a font-incompatibility issue that probably took effect upon the restart. I don't see how the this installer could have caused the font issue, especially considering that it actually failed (due to lack of `zlib` on your computer). Have you tried removing/changing the specific font-set you are using? When did you adopt that font-set? What is its name?

**Comment by the-vampiire** [comment]
the font issues started before i restarted. my terminal froze with the error messages. when i tried opening a new terminal tab it suddenly went all black. then my menu bar stopped responding (it only showed blacked out outlines of the dropdown menus).

i noticed the firefox issue after restarting which is when i made this post. 

i dont use chrome but here is safari for reference (even worse than firefox!):

<img width="1037" alt="Screen Shot 2019-07-19 at 11 59 24 AM" src="https://user-images.githubusercontent.com/25523682/61548882-442ced00-aa3e-11e9-9cdd-790db2ef6cda.png">

my thinking is that somehow python got corrupted. i believe nerdfont relies on python through homebrew for its fonts. whats strange is that i only use nerdfont in my terminal. i never changed any font settings in firefox (not sure what the default is). 

i adopted the nerdfonts about 4 months ago and have not had any issues like this throughout that time. i have not installed anything new or done anything different on my machine besides trying to install the elb cli tool last night.

**Comment by the-vampiire** [comment]
alright i finally resolved this. here are the steps i took:

- uninstall awscli through homebrew
- uninstall python3 through homebrew
- osx Font Book -> file -> restore standard fonts
- removed cached font files `$ sudo atsutil databases -remove`

up to this point the issue persisted but im including them for reference

- restarted in safe mode, shut down, turn on (hold shift key), log in. once booted turn off the machine then turn it back on

this ended up resolving it. by any means ill pass on the CLI, leaving this all here for reference in case someone else encounters the same issue

**Comment by rahulrajaram** [comment]
I'm glad that your problem is resolved.

> my thinking is that somehow python got corrupted.

I think so too, however, I should clarify some possible assumptions.

Clearly, this package did not install Python. Even when it does install successfully, you have to manually add it to PATH. That being said, had you installed Python through this package, it would possibly have caused the same problem, but that is a bug in nerd-font.

> - uninstall awscli through homebrew

Do you mean `awsebcli`? This repository has no relation to the awscli.

**Comment by the-vampiire** [comment]
> Clearly, this package did not install Python.

i must have misread the script out stating "Installing Python 3.7.2"?

```sh
5. Installing Python 3.7.2. This step may take a few minutes
************************************************************
python-build: use openssl from homebrew
python-build: use readline from homebrew
Downloading Python-3.7.2.tar.xz...
-> https://www.python.org/ftp/python/3.7.2/Python-3.7.2.tar.xz
Installing Python-3.7.2...
```
i really dont know enough about how nerd-font works to comment on it. but i know ive had no conflicts with it before (including installing other python related tools)

> Do you mean awsebcli? This repository has no relation to the awscli.

yes the aws cli tool. sorry if i presented it as being associated with this package. i actually had to uninstall it as it was a blocking dependent on uninstalling python through homebrew.
