### ISSUE TITLE
Unable to run awsebcli because of outdated botocore on python 3.7.0 #3357 #4368

### ISSUE THREAD

**Issue by Ujjala** [aws/aws-elastic-beanstalk-cli-setup#44]
I am facing the following issue while running awscli
C:\Users\admin>eb init -p python-3.7
Traceback (most recent call last):
File "C:\Users\admin\AppData\Roaming\Python\Python37\Scripts\eb-script.py", line 6, in 
from pkg_resources import load_entry_point
File "c:\program files\python37\lib\site-packages\pkg_resources_init_.py", line 3191, in 
@call_aside
File "c:\program files\python37\lib\site-packages\pkg_resources_init.py", line 3175, in call_aside
f(*args, **kwargs)
File "c:\program files\python37\lib\site-packages\pkg_resources_init.py", line 3204, in initialize_master_working_set
working_set = WorkingSet.build_master()
File "c:\program files\python37\lib\site-packages\pkg_resources_init.py", line 583, in build_master
ws.require(requires)
File "c:\program files\python37\lib\site-packages\pkg_resources_init.py", line 900, in require
needed = self.resolve(parse_requirements(requirements))
File "c:\program files\python37\lib\site-packages\pkg_resources_init.py", line 786, in resolve
raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'botocore<1.13,>=1.12.29' distribution was not found and is required by awsebcli

I have added the reference number of the similar issue which shows it has closed

**Comment by ChaseAllbee** [comment]
Hey Ujjala,

I'm taking a look into this problem to see if I can recreate it. In the meantime could you let me know what version of the awsebcli you're running?

**Comment by Ujjala** [comment]
the latest version 0.1.2

**Comment by rahulrajaram** [comment]
@Ujjala , thanks for reaching out.

You are seeing the error because you have not installed `botocore`. There is no indication of how you installed the AWS CLI.

What are these reference issues (3357, 4368) you are alluding to? I get the sense you are mixing up repositories.

**Comment by Ujjala** [comment]
Hi Chase and Rahul,
Thanks for the responses
I followed the instructions on aws using bundled_installer to install awscli, which showed a success message as per Demo.png.
I have botcore installed in one of my virtualenv but not on my root, let me install botcore on root and will revert if it works

**Comment by Ujjala** [comment]
tried installing botcore in the root getting the following error, my O.S is Windows 10.
--------------------------------------------------------------------------------------------------------------
pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
Collecting botcore
  Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/botcore/
  Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/botcore/
  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/botcore/
  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/botcore/
  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/botcore/
  Could not fetch URL https://pypi.org/simple/botcore/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/botcore/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) - skipping
  Could not find a version that satisfies the requirement botcore (from versions: )
No matching distribution found for botcore
--------------------------------------------------------------------------------------------------------------

**Comment by rahulrajaram** [comment]
> I followed the instructions on aws using bundled_installer to install awscli, which showed a success message as per Demo.png.

Did you try executing `eb` immediately after that? You should not have had to do anything else after that.

**Comment by Ujjala** [comment]
yes I tried executing eb after the installing was a success

**Comment by rahulrajaram** [comment]
Okay. Anyway, "C:\Users\admin\AppData\Roaming\Python\Python37\Scripts\eb-script.py", which is the `eb` you are using, is broken. It was not installed by this script. If you uninstall that particular version (I think `pip uninstall awsebcli` should do it) and then rerun bundled installer, you should have a working CLI. Let me know if that works.

**Comment by Ujjala** [comment]
Thanks will try and update
