### ISSUE TITLE
Install on Mac osx won't load Python

### ISSUE THREAD

**Issue by kemmieg** [aws/aws-elastic-beanstalk-cli-setup#45]
I'm fairly new at running command line scripts but I followed the instructions and when it got to the python build I got the error "Inspect or clean up working tree at....." I've looked at the log but it's very long and complicated. As far as I can tell via the log it says "Because of configuration changes, you MUST do the following before building. make depend making all in crypto..." then there is a whole bunch of stuff and the only thing I recognize is Xcode.app.  I'm attaching the log file maybe someone can make some sense out of it since I can't figure out what is going on
[python-build.20190731160854.16492.log](https://github.com/aws/aws-elastic-beanstalk-cli-setup/files/3457230/python-build.20190731160854.16492.log)

**Comment by rahulrajaram** [comment]
Hi @kemmieg , the log output shows that you are missing zlib on your computer.

Can you take a look at the troubleshooting section for OS X in the README to address this?

**Comment by kemmieg** [comment]
Thank you I will take a look

Kem Griffin
Web Developer/Graphic Designer
702.354.9380

**Comment by quarac** [comment]
Mojave 10.14.6 
Solved by executing this:
sudo installer -pkg /Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg -target /
