### ISSUE TITLE
Build Failed 10.13.5 (After Troubleshooting Step)

### ISSUE THREAD

**Issue by dunhampa** [aws/aws-elastic-beanstalk-cli-setup#46]
```
==============================================
I. Installing Python                          
==============================================

*************************************************************
1. Determining whether pyenv is already installed and in PATH
*************************************************************
    - pyenv was not found in PATH.

*********************************************************
2. Determining whether pyenv should be cloned from GitHub
*********************************************************
    - pyenv git repository already cloned to /Users/peterdunham/.pyenv-repository. Won't attempt to clone again.

*******************************************
3. Temporarily export necessary pyenv paths
*******************************************

****************************************************************************
4. Checking whether Python can be downloaded (through curl, wget, or aria2c)
****************************************************************************

************************************************************
5. Installing Python 3.7.2. This step may take a few minutes
************************************************************
python-build: use openssl from homebrew
python-build: use readline from homebrew
Downloading Python-3.7.2.tar.xz...
-> https://www.python.org/ftp/python/3.7.2/Python-3.7.2.tar.xz
Installing Python-3.7.2...
python-build: use readline from homebrew
ERROR: The Python ssl extension was not compiled. Missing the OpenSSL lib?

Please consult to the Wiki page to fix the problem.
https://github.com/pyenv/pyenv/wiki/Common-build-problems


BUILD FAILED (OS X 10.13.5 using python-build 20180424)
```

**Comment by rahulrajaram** [comment]
@dunhampa , can you confirm the following are the troubleshooting steps you have alluded to in the Issue title?

```bash
brew install zlib openssl readline
CFLAGS="-I$(brew --prefix openssl)/include -I$(brew --prefix readline)/include -I$(xcrun --show-sdk-path)/usr/include" LDFLAGS="-L$(brew --prefix openssl)/lib -L$(brew --prefix readline)/lib -L$(brew --prefix zlib)/lib"

```

**Comment by dunhampa** [comment]
@rahulrajaram yes, I just reconfirmed that is the specific commands I ran for troubleshooting

I am wondering if I am having issues with multiple python versions/installs.  

Is my anaconda3 install causing a conflict?:

(base) Peters-MacBook-Pro-4:~ peterdunham$ which python
/Users/peterdunham/anaconda3/bin/python
(base) Peters-MacBook-Pro-4:~ peterdunham$ 

Thanks

**Comment by dunhampa** [comment]
Another thought - do I need install  pyenv as a prereq?

**Comment by rahulrajaram** [comment]
@dunhampa ,

The answer to both your questions is "no".

The core of the problem is certainly that OpenSSL cannot be found during Python installation. Can you tell me what the output of the following command is?

```bash
brew --prefix openssl
```

**Comment by dunhampa** [comment]
@rahulrajaram  thanks for replies

output of `brew --prefix openssl`

is

`/usr/local/opt/openssl`

**Comment by rahulrajaram** [comment]
@dunhampa, thanks.

Now I am not sure what the problem is.

In the meantime, you can use the Python associated with Conda and run the following to get around your problem:

```
pip install virtualenv
</path/to/some/python/on/your/computer> scripts/ebcli_installer.py

**Comment by dunhampa** [comment]
@rahulrajaram 

ase) Peters-MacBook-Pro-4:~ peterdunham$ pip install virtualenv
Requirement already satisfied: virtualenv in ./.local/lib/python3.7/site-packages (16.7.2)
(base) Peters-MacBook-Pro-4:~ peterdunham$ /usr/local/bin/python3 ./aws-elastic-beanstalk-cli-setup/scripts/ebcli_installer.py 

***********************************
1. Locating virtualenv installation
***********************************
ERROR: Could not find and "virtualenv" installed. Ensurevirtualenv is installed and that it is in PATH before executingthis script.

**Comment by dunhampa** [comment]
I got a successful install when running 

`pip**3** install virtualenv`

I followed instructions to add to path - but now getting another error

`(base) Peters-MacBook-Pro-4:~ peterdunham$ source ~/.bash_profile
(base) Peters-MacBook-Pro-4:~ peterdunham$ eb --version
Traceback (most recent call last):
  File "/Users/peterdunham/.ebcli-virtual-env/bin/eb", line 6, in <module>
    from ebcli.core.ebcore import main
ModuleNotFoundError: No module named 'ebcli'
`

Another piece of info is I had another active install in Python 2:

`(base) Peters-MacBook-Pro-4:~ peterdunham$ eb --version
EB CLI 3.14.6 (Python 2.7.1)`

**Comment by rahulrajaram** [comment]
Is `base` a virtual env? If so, can you retry `eb --version` after deactivating `base`?

**Comment by dunhampa** [comment]
base is not a virtual env. I must have installed at system level at some point.

I tried to install within a virtual environment and get the following error:

`ERROR: This script cannot be executed inside a virtual environment.`

**Comment by rahulrajaram** [comment]
> I must have installed at system level at some point.

Can you clarify what exactly it is that you are talking about?

> I tried to install within a virtual environment and get the following error:

This is expected behaviour. You are expected to not already be inside a vrtualenv when you run the ebcli_installer.

**Comment by NoumanAhmad448** [comment]
In case someone is having this issue. Please refer to my comment [here](https://github.com/aws/aws-elastic-beanstalk-cli-setup/issues/28#issuecomment-1741946929)
