### ISSUE TITLE
BUILD FAILED (OS X 10.14.6 using python-build 20180424)

### ISSUE THREAD

**Issue by ShonFrazier** [aws/aws-elastic-beanstalk-cli-setup#53]
macOS 10.14.6
GNU bash 5.0.9
Python 3.7.4 already installed

Different error (as log shows) from issue #47. bundled_installer fails to install Python 3.7.2 with the error above, and last 10 log lines below.

- [x] **I have reviewed the troubleshooting tips described [here](https://github.com/aws/aws-elastic-beanstalk-cli-setup/issues/47#issuecomment-520603720) and they do not solve my problem**

```
************************************************************
5. Installing Python 3.7.2. This step may take a few minutes
************************************************************
python-build: use openssl from homebrew
python-build: use readline from homebrew
Downloading Python-3.7.2.tar.xz...
-> https://www.python.org/ftp/python/3.7.2/Python-3.7.2.tar.xz
Installing Python-3.7.2...
python-build: use readline from homebrew

BUILD FAILED (OS X 10.14.6 using python-build 20180424)

Inspect or clean up the working tree at /var/folders/hp/95jl23l97xlcm8_011nx_0_m0000gn/T/python-build.20190817173947.43610
Results logged to /var/folders/hp/95jl23l97xlcm8_011nx_0_m0000gn/T/python-build.20190817173947.43610.log

Last 10 log lines:
checking MACHDEP... checking for --without-gcc... no
checking for --with-icc... no
checking for gcc... clang
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... configure: error: in `/var/folders/hp/95jl23l97xlcm8_011nx_0_m0000gn/T/python-build.20190817173947.43610/Python-3.7.2':
configure: error: cannot run C compiled programs.
If you meant to cross compile, use `--host'.
See `config.log' for more details
   Exiting due to failure
```

**Comment by rahulrajaram** [comment]
@ShonFrazier , I'm sorry for the late response. Can you retry after running the following command:

```shell
xcode-select --install
```

**Comment by rahulrajaram** [comment]
Since you already have a Python 3.7 installed, you can unblock yourself by now running:

```
python ./scripts/ebcli_installer.py
```

**Comment by ShonFrazier** [comment]
> @ShonFrazier , I'm sorry for the late response. Can you retry after running the following command:
> 
> ```shell
> xcode-select --install
> ```

CLI tools already installed. This didn't do anything.

> Since you already have a Python 3.7 installed, you can unblock yourself by now running:
> 
> ```
> python ./scripts/ebcli_installer.py
> ```

This did it. Thanks.
