### ISSUE TITLE
fyi, tl;dr installation steps, it's already available for mac/brew

### ISSUE THREAD

**Issue by ggmartins** [aws/aws-elastic-beanstalk-cli-setup#61]
wouldn't be better to just start the readme with the obvious command for non-devs
brew install aws-elasticbeanstalk
..since this is already available? maybe apt yum too?
thanks, G

**Comment by rahulrajaram** [comment]
Hi @ggmartins, sorry for the late response and your suggestion. Indeed, this was though about. The rationale against it has been expressed [here](https://github.com/aws/aws-elastic-beanstalk-cli-setup#43-on-macos-or-linux-systems-with-brew-is-this-better-than-brew-install-awsebcli).
