### ISSUE TITLE
Error when running eb create --cfg with specified path  of "../"

### ISSUE THREAD

**Issue by roeera** [aws/aws-elastic-beanstalk-cli-setup#63]
- OS: OS X
 - Shell : Bash , Zsh

When trying to create new env based on pre saved config file (e.g. test.cfg.yml) that located on upper directory, receiving an error "ERROR: ServiceError - 1 validation error detected: Value '../templates/saved_configs/test' at 'templateName' failed to satisfy constraint: Member must satisfy regular expression pattern: [^/]+"

But, if I copy the config locally (same folder i'm running the eb create), there is no error and things are working properly.

Please fix.

Thank you.

**Comment by rahulrajaram** [comment]
@roeera ,

Thanks for reaching out. Please note that the recommended place to put your CFG templates is in `.elasticbeanstalk/saved_configs/` (as described [here](https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/environment-configuration-methods-during.html#configuration-options-during-ebcli-savedconfig)).
