### ISSUE TITLE
Ubuntu post installation instructions won't work

### ISSUE THREAD

**Issue by caligo-erik** [aws/aws-elastic-beanstalk-cli-setup#66]
**1. Please specify the following:**
 - OS: [e.g. OS X, Ubuntu, Windows, etc.]: Ubuntu 18.04
 - Shell (Bash, PowerShell, Zsh, etc.): Bash

- [x] **I have reviewed the troubleshooting tips described [here]() and they do not solve my problem**

**2. Description**
Please describe the problem you are facing as precisely as possible in this section

The post install instructions to add eb to PATH were:
`echo 'export PATH="/home/user/.ebcli-virtual-env/executables:$PATH"' >> ~/.bash_profile && source ~/.bash_profile
`
But I couldn't call `eb` from console. I changed the command to add it to .bashrc and worked:
`echo 'export PATH="/home/user/.ebcli-virtual-env/executables:$PATH"' >> ~/.bashrc && source ~/.bashrc`

Same applies for the entry for python.

**Comment by rahulrajaram** [comment]
@caligo-erik , thanks for reaching out.

I'm curious to know whether you opened a new terminal to execute `eb` in after the installation.
