### ISSUE TITLE
I am having same issure. 

### ISSUE THREAD

**Issue by JBozarov** [aws/aws-elastic-beanstalk-cli-setup#73]
**1. Please specify the following:**
 - OS: [e.g. OS X, Ubuntu, Windows, etc.]: ___
 - Shell (Bash, PowerShell, Zsh, etc.): ____

- [ ] **I have reviewed the troubleshooting tips described [here]() and they do not solve my problem**

**2. Description**
Please describe the problem you are facing as precisely as possible in this section

**Comment by rahulrajaram** [comment]
@JBozarov , please describe your issue in detail.
