### ISSUE TITLE
I have installed but I keep getting ERROR: NotAuthorizedError - Operation Denied. Access Denied. How can I uninstall?

### ISSUE THREAD

**Issue by ibukun-paystack** [aws/aws-elastic-beanstalk-cli-setup#74]
**1. Please specify the following:**
 - OS: [e.g. OS X, Ubuntu, Windows, etc.]: __OS X_
 - Shell (Bash, PowerShell, Zsh, etc.): ____

- [x] **I have reviewed the troubleshooting tips described [here]() and they do not solve my problem**

**2. Description**
Please describe the problem you are facing as precisely as possible in this section

After installation, running eb init gives me ERROR: NotAuthorizedError - Operation Denied. Access Denied. I set the profile in my environment variable and also in my ~/.aws/credentials file but I had no luck running eb init or eb init --profile eb-cli. 

I also want to know how to completely uninstall as there is no uninstall script in the repository

**Comment by rahulrajaram** [comment]
1. To debug your access-denied problem:

run `eb init --profile eb-cli --debugboto`

This will show you deepr logs than just `--debug`. There will be an indication of the AWS Access ID used by the EBCLI. Confirm that this is the access ID you wish to use.

2. You can remove `~/.ebcli-virtual-env` and remove `ebcli-virtual-env/executables/eb` from upir `PATH` key word to uninstall the EBCLI..

**Comment by rahulrajaram** [comment]
@ibukun-paystack please reopen the Issue if you have related questions. Closing for now.
