### ISSUE TITLE
Missing uninstallation instructions

### ISSUE THREAD

**Issue by cwfoo** [aws/aws-elastic-beanstalk-cli-setup#79]
**1. Please specify the following:**
 - OS: [e.g. OS X, Ubuntu, Windows, etc.]: Ubuntu
 - Shell (Bash, PowerShell, Zsh, etc.): any

- [x] **I have reviewed the troubleshooting tips described [here]() and they do not solve my problem**

**2. Description**
 There are no instructions for uninstalling `eb`.

**Comment by rahulrajaram** [comment]
Duplicate of #78 . Closing.
