### ISSUE TITLE
macOS Uninstall Instructions missing

### ISSUE THREAD

**Issue by michaelbrawn** [aws/aws-elastic-beanstalk-cli-setup#82]
**1. Please specify the following:**
 - OS: [e.g. OS X, Ubuntu, Windows, etc.]: macOS
 - Shell (Bash, PowerShell, Zsh, etc.): Zsh

- [x] **I have reviewed the troubleshooting tips described [here]() and they do not solve my problem**

**2. Description**
Readme is missing uninstall instructions for macOS.

**Comment by rahulrajaram** [comment]
@michaelbrawn , thanks for bringing this issue up. In the meantime, you can:

- remove the `~/.ebcli-virtual-env` dir
- remove the `~/.ebcli-virtual-env/executables` dir from `$PATH`

**Comment by rahulrajaram** [comment]
Duplicate of #78 . Closing.
