### ISSUE TITLE
Specify python version to use

### ISSUE THREAD

**Issue by punisher21maximum** [aws/aws-elastic-beanstalk-cli-setup#86]
**1. Please specify the following:**
 - OS:  Windows : 
 - Shell : cmd  
- [ ] **I have reviewed the troubleshooting tips described [https://github.com/aws/aws-elastic-beanstalk-cli-setup#4-frequently-asked-questions]() and they do not solve my problem**

**2. Doc does not say how to use specific version of python**
for python installation doc says to use
python . \......
where as we should use
py -3.6 or py -3.7 in place of python. Otherwise it uses python 2.7 if you have it. To be precise about the version is important

`python .\aws-elastic-beanstalk-cli-setup\scripts\ebcli_installer.py`

should be

`py -3.6 .\aws-elastic-beanstalk-cli-setup\scripts\ebcli_installer.py`

**Comment by rahulrajaram** [comment]
See under ["Advanced Use"](https://github.com/aws/aws-elastic-beanstalk-cli-setup#3-advanced-use):

```
python scripts/ebcli_installer.py --python-installation /path/to/some/python/on/your/computer
```

**Comment by punisher21maximum** [comment]
Yes I have seen that. So?

**Comment by punisher21maximum** [comment]
Incase its not an issue according to you
